import { MaterialProduct, ProjectCalculatorType } from './types';

export const TRANSLATIONS = {
  fa: {
    appName: "ایران مصالح",
    appSubtitle: "مرجع تخصصی مصالح ساختمانی یزد",
    locationBadge: "یزد، قطب تولید مصالح ایران | ارسال به سراسر کشور و صادرات",
    navHome: "صفحه اصلی",
    navCatalog: "کاتالوگ محصولات",
    navCalculator: "محاسبه‌گر مصالح",
    navHeritage: "اصالت خاک یزد",
    navContact: "ارتباط با ما",
    navQuoteCart: "پیش‌فاکتور",
    heroTitlePart1: "شالوده اصیل معماری،",
    heroTitlePart2: "از خاک یزد تا سازه‌های نوین",
    heroDesc: "پایگاه مستقیم توزیع و صادرات ممتازترین مصالح ساختمانی کویر یزد. از آجرهای رسی سنتی و کاشی‌های ممتاز میبد تا سنگ‌های تراورتن ماندگار و فولاد مهندسی‌شده با استانداردهای نوین.",
    btnCatalog: "مشاهده کاتالوگ محصولات",
    btnCalculateShortcut: "برآورد هوشمند نیاز پروژه",
    statProjects: "۱۲,۰۰۰+",
    statProjectsLabel: "پروژه مجهز شده در سراسر کشور",
    statQuarries: "۴۵+",
    statQuarriesLabel: "معادن و کارخانجات انحصاری تحت پوشش",
    statExport: "۱۸+",
    statExportLabel: "کشور مقصد صادرات کاشی و سنگ یزد",
    statSatisfied: "۹۹٪",
    statSatisfiedLabel: "رضایت مهندسان و معماران کشور",
    
    // Catalog
    catalogTitle: "کاتالوگ مصالح ممتاز",
    catalogSubtitle: "محصولات برگزیده تولیدشده با خاک حاصل‌خیز، سنگ طبیعی و صنعت نوین یزد",
    allCategories: "همه دسته‌ها",
    categoryTraditional: "آجر و سفال سنتی",
    categoryTiles: "کاشی و سرامیک پرسلان",
    categoryStones: "سنگ‌های طبیعی نما و کف",
    categoryCement: "سیمان، گچ و ترکیبات",
    categorySteel: "فولاد و میلگرد سازه",
    addToQuote: "افزودن به پیش‌فاکتور",
    addedToQuote: "اضافه شد",
    priceToman: "تومان",
    specsLabel: "مشخصات فنی",
    unitPrice: "قیمت پایه",
    unitLabel: "واحد خرید",
    leadTime: "تحویل تقریبی",
    days: "روز کاری",
    instantDelivery: "تحویل فوری از انبار یزد",

    // Calculator
    calcTitle: "محاسبه‌گر هوشمند مصالح ساختمانی",
    calcSubtitle: "ابعاد پروژه خود را وارد کنید تا حجم دقیق مصالح، وزن بار و برآورد هزینه فرضی به صورت زنده محاسبه شود.",
    calcConcreteWall: "دیوار چینی (بلوک سفالی یا آجر)",
    calcConcreteSlab: "بتن‌ریزی فونداسیون و سقف",
    calcTiling: "کاشی و سرامیک‌کاری دیواره/کف",
    calcPlastering: "سفیدکاری و گچ‌کاری داخلی",
    dimensionsInput: "ابعاد مورد نیاز برای محاسبه",
    wallLength: "طول دیوار",
    wallHeight: "ارتفاع دیوار",
    wallThickness: "ضخامت دیوار (معولا ۱۰، ۱۵ یا ۲۰ سانتی‌متر)",
    slabLength: "طول بتن‌ریزی",
    slabWidth: "عرض بتن‌ریزی",
    slabThickness: "ضخامت بتن (عمق)",
    calcResultTitle: "نتایج محاسبه و ارزیابی فنی باربری",
    estimatedMaterials: "مصالح تخمینی مورد نیاز:",
    estimatedCost: "برآورد فرضی هزینه پایه:",
    estimatedWeight: "وزن تقریبی محموله حمل‌و‌نقل:",
    requiredTruckType: "وسیله حمل‌و‌نقل پیشنهادی:",
    pickupTruck: "وانت نیسان (تا ۲.۲ تن)",
    lightTruck: "خاور / کامیونت (تا ۵ تن)",
    heavyTruck: "کامیون تک/جفت (تا ۱۵ تن)",
    trailerTruck: "تریلی کفی هجده‌چرخ (تا ۲۵ تن)",
    formulaUsed: "فرمول محاسباتی کاربردی:",
    applyToQuoteBtn: "اعمال نتایج مستقیم به پیش‌فاکتور",

    // Heritage Section
    heritageTitle: "چرا خاک و سنگ کویر یزد معجزه می‌کند؟",
    heritageSubtitle: "راز ماندگاری بادگیرها، مسجد جامع تاریخی و مقاومت استثنایی مصالح معدنی یزد",
    heritageTabClay: "اکسیر خاک یزد",
    heritageTabStone: "معادن فراملی تراورتن",
    heritageTabTile: "فناوری روز کاشی و سرامیک",
    heritageClayTitle: "رس مرغوب فلات ایران با مقاومت حرارتی استثنایی",
    heritageClayDesc: "خاک رس دشت‌های پیرامون یزد به دلیل درصد بهینه اکسید آهن و ترکیبات آلومینوسیلیکات طبیعی، فاقد شوره و گچ اضافی است. این خاک هنگام پخت در دمای بالا، بلورهایی تشکیل می‌دهد که در برابر نوسانات مهیب دمای کویر (سرمای خشک زمستان و گرمای تابستان) مقاومت بی‌نظیری دارد. آجرهای سنتی یزد قرن‌هاست بدون گسستگی، ستون‌های تاریخی این سرزمین را حفظ کرده‌اند.",
    heritageStoneTitle: "سنگ‌های مرمریت و تراورتن مقاوم به فرسایش باران‌های اسیدی",
    heritageStoneDesc: "معادن اطراف استان یزد به موازات کویرهای غنی مرکزی، خاستگاه لوکس‌ترین کوپ‌های سنگ تراورتن کشور با تخلخل بسیار منسجم است. این تخلخل ویژه سبب می‌شود ملات به عمق سنگ نفوذ کرده و ثباتی همیشگی در ارتفاع نما ایجاد کند. ماندگاری رنگ در برابر اشعه مستقیم فرابنفش تخصص طبیعی این سنگ‌هاست.",
    heritageTileTitle: "یزد؛ پایتخت بی‌رقیب صنعت پیشرفته کاشی و پرسلان خاورمیانه",
    heritageTileDesc: "با تلفیق ماشین‌آلات تمام اتوماتیک پخت چرخشی ایتالیایی و خاک نسوز غنی، کاشی و سرامیک‌های پرسلان تولیدی یزد از جمله مارک‌های طراز اول صادراتی هستند که مقاومت خمشی تا ۴۵ نیوتن بر میلی‌متر مربع و جذب آب زیر ۰.۵ درصد را ثبت کرده و مناسب شدیدترین شرایط صنعتی سراسر دنیا تدارکات شده‌اند.",

    // Cart / Queue Inquiry Preview
    quoteTitle: "پیش‌فاکتور هوشمند و ثبت استعلام قیمت زنده",
    quoteSubtitle: "هیچ‌گونه پرداخت آنلاین مستقیمی صورت نمی‌گیرد. اقلام را تایید کنید تا فورا پیش‌فاکتور معتبر صادر شده و کارشناسان ترابری و لجستیک یزد با شما تماس حاصل کنند.",
    cartEmpty: "سبد پیش‌فاکتور شما خالی است. از کاتالوگ محصولات فوق، مواردی را اضافه نمایید.",
    productName: "نام محصول",
    quantity: "مقدار سفارش",
    priceEstimate: "بهاء تخمینی",
    actionRemove: "حذف",
    formHeading: "فرم ثبت نهایی و آدرس‌دهی بارگیری",
    clientNameLabel: "نام و نام‌خانوادگی کارفرما / پیمانکار",
    clientPhoneLabel: "شماره همراه معتبر (جهت هماهنگی ترابری و بارنامه)",
    locationLabel: "کارگاه یا پروژه مقصد (مثال: شیراز، منطقه معالی‌آباد)",
    urgencyLabel: "اولویت تحویل و بارگیری",
    urgencyRoutine: "عادی (ارسال متداول طی ۲ تا ۴ روز کاری)",
    urgencyUrgent: "فوری (آماده‌باش ترانزیت، بارگیری طی ۲۴ ساعت)",
    urgencyFuture: "رزرو برای ماه آینده (تثبیت قیمت و نگهداری در انبار یزد)",
    btnSubmitQuote: "صدور صادر صادر پیش‌فاکتور و ثبت بارنامه موقت",
    quoteSuccessHeader: "پیش‌فاکتور هوشمند صادر شد!",
    quoteSuccessText: "مدارک تخصصی ارزیابی قیمت و بارگیری کالاهای شما در سامانه ایران مصالح با موفقیت رزرو گردید. فورا با شماره همراه ثبت‌شده جهت استعلام کرایہ تریلی یا کامیون تماس گرفته خواهد شد.",
    receiptNo: "شماره پیگیری پیش‌فاکتور:",
    printReceipt: "چاپ فاکتور و فیش انبارداری",
    closeReceipt: "ثبت استعلام جدید / بستن",

    // Contact
    contactTitle: "دفتر مرکزی و هماهنگی لجستیک یزد",
    contactSubtitle: "سفارش مستقیم و ارتباط بی‌واسطه با کارخانه‌ها و معادن استان یزد",
    addressLabel: "آدرس دفتر و انبار مرکزی:",
    addressText: "یزد، شهرک صنعتی سیمرغ، بلوار کارگر، تقاطع کاشی‌سازان، مجتمع تجاری ایران مصالح",
    phoneLabel: "تلفن‌های پشتیبانی زنده و استعلام قیمت لحظه‌ای:",
    emailLabel: "پست الکترونیکی بازرگانی و صادرات:",
    workingHoursLabel: "ساعات کار هماهنگی ترابری:",
    workingHoursText: "همه روزه یکسره از ساعت ۷:۳۰ صبح الی ۲۱:۰۰ شب (پنجشنبه‌ها تا ۱۴)",
    whatsappContact: "ارسال مستقیم پیش‌فاکتور به مدیریت فروش در واتس‌اپ"
  },
  en: {
    appName: "Iran Masaleh",
    appSubtitle: "Yazd's Sourced Premium Construction Materials",
    locationBadge: "Yazd, Iran's Mineral Hub | Domestic & International Export Supply",
    navHome: "Home",
    navCatalog: "Products Catalog",
    navCalculator: "Material Calculator",
    navHeritage: "Our Heritage",
    navContact: "Contact Us",
    navQuoteCart: "Quotation Basket",
    heroTitlePart1: "The Core of Architecture,",
    heroTitlePart2: "From Yazd Clay to Global Structures",
    heroDesc: "Direct portal distributing premium construction materials from Yazd deserts. Sourcing authentic structural clay blocks, world-famous Meybod blue glazed tiles, heavy strength steel alloys, and thermal-insulated travertine stone blocks for elite worldwide architectural projects.",
    btnCatalog: "Explore Materials Catalog",
    btnCalculateShortcut: "Run AI Project Estimator",
    statProjects: "12,000+",
    statProjectsLabel: "Completed Structures Armed Nationwide",
    statQuarries: "45+",
    statQuarriesLabel: "Exclusive Quarries & Automated Kilns Managed",
    statExport: "18+",
    statExportLabel: "Foreign Destination Countries Sourcing Yazd Tile",
    statSatisfied: "99%",
    statSatisfiedLabel: "Structural Engineering Satisfaction Rate",
    
    // Catalog
    catalogTitle: "Premium Materials Catalog",
    catalogSubtitle: "Finest natural travertine, durable desert clay kiln bricks, and export-grade high-absorption ceramics from Yazd",
    allCategories: "All Departments",
    categoryTraditional: "Clay & Traditional Bricks",
    categoryTiles: "Porcelain & Ceramic Tiles",
    categoryStones: "Facade Travertine & Granite",
    categoryCement: "Cements & Micropor Plasters",
    categorySteel: "Structural Steel & Ironworks",
    addToQuote: "Add to Inquiry",
    addedToQuote: "Added",
    priceToman: "Toman",
    specsLabel: "Technical Specifications",
    unitPrice: "Base Price",
    unitLabel: "Sales Unit",
    leadTime: "Estimated Transit",
    days: "Business Days",
    instantDelivery: "Immediate loading at Yazd Freight Terminal",

    // Calculator
    calcTitle: "Smart Material & Transport Duty Estimator",
    calcSubtitle: "Input your actual masonry or concrete dimensions below to dynamically calculate quantities, dry weight, and estimated freight sizes.",
    calcConcreteWall: "Brick/Clay Block Masonry Wall",
    calcConcreteSlab: "Structural Concrete Foundation/Slab",
    calcTiling: "Tile Covering (Walls & Floors)",
    calcPlastering: "Interior Plastering & Stucco Finish",
    dimensionsInput: "Required Structural Fields",
    wallLength: "Wall Length",
    wallHeight: "Wall Height",
    wallThickness: "Wall Thickness (approx. 10, 15, or 20 cm)",
    slabLength: "Pouring Length",
    slabWidth: "Pouring Width",
    slabThickness: "Pouring Depth/Thickness",
    calcResultTitle: "Fulfillment & Logistical Analytics",
    estimatedMaterials: "Estimated Quantities Required:",
    estimatedCost: "Theoretical Base Cost Estimate:",
    estimatedWeight: "Calculated Shipping Deadweight:",
    requiredTruckType: "Recommended Logistics Vehicle:",
    pickupTruck: "Zamyad Pickup (Up to 2.2 Tons)",
    lightTruck: "Medium Cargo Truck (Up to 5 Tons)",
    heavyTruck: "Heavy Double-Axle Cargo Truck (Up to 15 Tons)",
    trailerTruck: "18-Wheeler Flatbed Trailer (Up to 25 Tons)",
    formulaUsed: "Applied Mathematical Model:",
    applyToQuoteBtn: "Save Calculations Directly to Quote List",

    // Heritage Section
    heritageTitle: "Why Yazd Desert Raw Gold (Clay) Dominates?",
    heritageSubtitle: "How centuries-old windcatchers, domes and mosques withstand extreme desert elements",
    heritageTabClay: "Alchemical Yazd Clay",
    heritageTabStone: "Export Travertine Quarries",
    heritageTabTile: "Advanced Porcelain High-Tech",
    heritageClayTitle: "Bentonite-rich pure clay with high temperature coefficient",
    heritageClayDesc: "Yazd's high-purity plains yield clay enriched with iron oxides and exceptional silicate ratios, virtually pre-washed of saltpeter (causing efflorescence). Baked at stable extreme kiln heats, the blocks lock in dense, insulating chambers giving superb structural breathability under grueling thermal shocks. The ancient structures testify to this raw perfection.",
    heritageStoneTitle: "Compact pore structure resisting acidic corrosion & extreme sun",
    heritageStoneDesc: "The mountains of Central Iran encircling Yazd deliver some of the best high-density travertine blocks. Their unique microporous matrix forms a superb mechanical lock with standard concrete slurry, ensuring facades never peel off, while holding natural luster despite grueling desert UV irradiation of 330 days a year.",
    heritageTileTitle: "Yazd: The tile and ceramic capital of the Middle East",
    heritageTileDesc: "Arming Italian Sacmi roll presses and high-speed rotary glazing, our factories formulate high-alumina clay base. Yazd porcelain features exceptional bending strengths above 45 N/mm² and water absorption ratios well below 0.5%, making them highly resistant to absolute freezing temperatures in export zones.",

    // Cart / Quote Inquiry Preview
    quoteTitle: "Quotation Generator & Freight Estimation",
    quoteSubtitle: "No online payment is completed here. Review your listed supplies, insert delivery credentials, and Yazd Logistics Hub will finalize custom discounted freight rates.",
    cartEmpty: "Your quotation basket is empty. Please select premium assets from the catalog above.",
    productName: "Item Name",
    quantity: "Required Quantity",
    priceEstimate: "Est. Subtotal",
    actionRemove: "Delete",
    formHeading: "Site & Receiver Logistics Details",
    clientNameLabel: "Contractor / Client Full Name",
    clientPhoneLabel: "Operational Contact Phone (For waybill registration)",
    locationLabel: "Project Shipping Address (e.g., Tabriz, East Zone)",
    urgencyLabel: "Cargo Dispatch Urgency Mode",
    urgencyRoutine: "Routine Dispatch (Loading & Shipping in 2-4 Business Days)",
    urgencyUrgent: "Express Transit (Immediate Dispatch within 24 Hours)",
    urgencyFuture: "Next-Month Reserve (Lock-in Base Price, Store in Yazd Silos)",
    btnSubmitQuote: "Generate Official Quote & Register Virtual Waybill",
    quoteSuccessHeader: "Smart PDF Waybill & Invoice Rendered!",
    quoteSuccessText: "Your inquiry has been stored at Iran Masaleh Shipping Portal. Our logistics dispatchers based in Yazd Terminal will dial your cell immediately to quote final trailer/truck freight costs.",
    receiptNo: "Virtual Booking Reference Serial:",
    printReceipt: "Print Official Raw Materials Invoice",
    closeReceipt: "Build New Invoice / Close Inquiry",

    // Contact
    contactTitle: "Yazd Global HQ & Logistics Freight Terminal",
    contactSubtitle: "Direct communication bypassing standard brokers and middle layers",
    addressLabel: "Head Office & Yards Complex Address:",
    addressText: "Yazd Industrial Zone, Simorgh Blvd, Kargar Avenue, Ceramicists Intersection, Iran Masaleh HQ Complex",
    phoneLabel: "Trading Desks Support & Direct Shipping Line:",
    emailLabel: "Corporate Trade & Export Bilateral division:",
    workingHoursLabel: "Freight Terminal Gates Working Hours:",
    workingHoursText: "Daily 07:30 AM to 21:00 PM (Thursdays 07:30 to 14:00) Iranian UTC+3.5",
    whatsappContact: "Send Saved Quote to Sales Director on WhatsApp"
  }
};

export const PRODUCTS: MaterialProduct[] = [
  {
    id: "yazd-clay-block-15",
    category: "traditional",
    nameFA: "سفال تیغه‌ای فوم‌دار ۱۵ درجه یک یزد",
    nameEN: "Premium 15cm Acoustic Foamed Clay Block",
    descriptionFA: "بلوک سفالی پانزده با دانسیته کنترل‌شده و فوم عایق پلیاستایرن تزریقی جهشی، مقاومت ۱۰۰٪ در برابر عبور صوت و هدایت حرارتی کویر.",
    descriptionEN: "Acoustical clay block made with refined pure desert silt. Incorporates integrated self-extinguishing EPS fireproof foam core to satisfy climate energy saving codes.",
    unitFA: "عدد",
    unitEN: "Piece",
    pricePerUnitTomans: 6500,
    densityKGperM3: 420,
    packWeightKG: 6.8,
    coverageM2PerUnit: 25, // Needs ~25 pieces per square meter of wall surface
    imageUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "ابعاد", labelEN: "Dimensions", valueFA: "۲۰ × ۲۰ × ۱۵ سانتی‌متر", valueEN: "20 x 20 x 15 cm" },
      { labelFA: "جنس خاک", labelEN: "Clay Origin", valueFA: "رس شسته‌شده عیار ممتاز کویر", valueEN: "High-grade refined desert clay" },
      { labelFA: "مقاومت فشاری", labelEN: "Compressive Strength", valueFA: "۳۵ کیلوگرم بر سانتی‌متر مربع", valueEN: "35 kg/cm²" },
      { labelFA: "عایق حرارتی", labelEN: "Insulation Ratio", valueFA: "دارای فوم فشرده اکسترود شده کناف", valueEN: "Equipped with dense premium EPS" },
    ]
  },
  {
    id: "yazd-traditional-paving-brick",
    category: "traditional",
    nameFA: "آجر قزاقی سنتی دست‌ساز یزدی ۴ سانتی",
    nameEN: "Yazdi Classic Hand-made Terracotta Brick",
    descriptionFA: "آجر پخته‌شده سنتی سن عیار با ته‌رنگ گلبهی و زرد خاکی ملایم، عالی برای دکوراسیون و نماسازی طاق‌های سنتی یزد.",
    descriptionEN: "Traditional hand-molded clay bricks baked in circular high-heat kiln tunnels. Stunning earthen color matching UNESCO heritage tones for unique facades.",
    unitFA: "قالب",
    unitEN: "Brick",
    pricePerUnitTomans: 3800,
    densityKGperM3: 1600,
    packWeightKG: 1.4,
    coverageM2PerUnit: 64, // ~64 bricks per M2
    imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "ابعاد قالب", labelEN: "Brick Size", valueFA: "۲۰ × ۱۰ × ۴ سانتی‌متر", valueEN: "20 x 10 x 4 cm" },
      { labelFA: "ثبات رنگ", labelEN: "Color Durability", valueFA: "۱۰۰٪ طبیعی و مقاوم به اشعه شدید آفتاب", valueEN: "100% stable under high direct UV" },
      { labelFA: "جذب آب", labelEN: "Water Absorption", valueFA: "کمتر از ۱۲ درصد وزنی", valueEN: "Less than 12% weight percentage" },
    ]
  },
  {
    id: "yazd-travertine-porcelain",
    category: "tiles",
    nameFA: "پرسلان اسلب طرح تراورتن ابریشمی میبد",
    nameEN: "Meybod Silk Travertine Porcelain Slab",
    descriptionFA: "سرامیک پرسلان فول بادی کالیبره با لعاب مات ابریشمی مقاوم در برابر لغزش، شبیه‌ساز کامل گران‌ترین نماهای سنگی.",
    descriptionEN: "Premium full-body rectified porcelain, digital glazed with ultra-realistic travertine vein-cut detailing. Anti-freeze and zero-water absorption.",
    unitFA: "متر مربع",
    unitEN: "Sq Meter",
    pricePerUnitTomans: 360000,
    densityKGperM3: 2400,
    packWeightKG: 32, // standard box weight
    coverageM2PerUnit: 1,
    imageUrl: "https://images.unsplash.com/photo-1615876234886-fd9a39faa97f?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "ابعاد تایل", labelEN: "Tile Dimensions", valueFA: "۱۲۰ × ۶۰ سانتی‌متر", valueEN: "120 x 60 cm" },
      { labelFA: "جذب آب پرسلان", labelEN: "Porosity Ratio", valueFA: "زیر ۰.۲ درصد (کاملاً ضد آب و یخ‌زدگی)", valueEN: "Under 0.2% (Freeze & Shock immune)" },
      { labelFA: "نوع پولیش", labelEN: "Finish Status", valueFA: "کالیبره بدون بند (نانو پولیش ابریشمی)", valueEN: "Rectified seamless nano-satin matte" },
    ]
  },
  {
    id: "meybod-turquoise-glazed",
    category: "tiles",
    nameFA: "کاشی سنتی هفت‌رنگ لعاب‌دار فیروزه‌ای میبد یزد",
    nameEN: "Traditional Meybod Azure Glazed Ceramic Tile",
    descriptionFA: "کاشی نگین‌دار دست‌ساز لعاب سنتی فیروزه‌ای مخصوص مساجد، رستوران‌های سنتی و تزئینات اصیل ایرانی.",
    descriptionEN: "Historic Persian blue glazed ceramics handcrafted in Meybod art workshops. Featuring deep cobalt oxide double glazing for absolute water-shield beauty.",
    unitFA: "عدد",
    unitEN: "Tile",
    pricePerUnitTomans: 19500,
    packWeightKG: 0.5,
    imageUrl: "https://images.unsplash.com/photo-1528255671579-01b9e182ed1d?auto=format&fit=crop&q=80&w=600",
    featured: false,
    specifications: [
      { labelFA: "ابعاد کاشی", labelEN: "Dimensions", valueFA: "۲۰ × ۲۰ سانتی‌متر", valueEN: "20 x 20 cm" },
      { labelFA: "طرح لعاب", labelEN: "Glazing Style", valueFA: "لعاب سنتی ترانسپارنت غنی از مس و روی", valueEN: "Rich mineral copper transparent glaze" },
      { labelFA: "ضخامت کاشی", labelEN: "Thickness", valueFA: "۸ میلی‌متر سنتی", valueEN: "8mm classic ceramic base" },
    ]
  },
  {
    id: "cream-travertine-stone-hajiabad",
    category: "stones",
    nameFA: "سنگ تراورتن کرم شکلاتی موج‌دار نما در جه یک",
    nameEN: "Supreme Veined Cream Travertine Facade Stone",
    descriptionFA: "سنگ طبیعی نما سوپر استخراج شده از معادن تفت و ابارکوه یزد، پر رنگ، با رزین کاری کوره با اپوکسی مقاوم به نور خورشید.",
    descriptionEN: "First-grade sedimentary cream limestone block slab for luxurious exterior facade works. Heat cured epoxy filled, providing extreme structural anchorage.",
    unitFA: "متر مربع",
    unitEN: "Sq Meter",
    pricePerUnitTomans: 590000,
    densityKGperM3: 2600,
    packWeightKG: 52,
    coverageM2PerUnit: 1,
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "ضخامت برش", labelEN: "Cut Thickness", valueFA: "۱.۸ سانتی‌متر استاندارد مهندسی", valueEN: "1.8 cm standard architect gauge" },
      { labelFA: "نوع تکنولوژی عمل‌آوری", labelEN: "Curing Tech", valueFA: "رزین اپوکسی ضد فرابنفش فشرده وکیوم", valueEN: "Anti-UV vacuum sealed epoxy resin" },
      { labelFA: "مقاومت در برابر شرایط جوی", labelEN: "Weather Resistance", valueFA: "مقاوم در برابر یخ‌زدگی مکرر و باران اسیدی", valueEN: "Immune to heavy thermal expand/frost" },
    ]
  },
  {
    id: "yazd-cement-type2",
    category: "cement",
    nameFA: "سیمان پرتلند تیپ ۲ پاکتی کارخانجات یزد",
    nameEN: "Yazd Portland Cement Type-II (50KG Bag)",
    descriptionFA: "سیمان مرغوب کلسیم آلومینات پودری تیره بالا با گرمازایی متوسط و مقاومت متوسط در برابر حمله سولفات‌های همجوار خاک کویر.",
    descriptionEN: "High-grade general architecture cement specializing in moderate sulfate resistance. Meets structural ISIRI standard designations with extreme sand bond.",
    unitFA: "پاکت ۵۰ کیلویی",
    unitEN: "50KG Bag",
    pricePerUnitTomans: 72000,
    densityKGperM3: 1500, // bulk dry density
    packWeightKG: 50,
    imageUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "وزن خالص هر پاکت", labelEN: "Net Weight", valueFA: "۵۰ کیلوگرم زمان بسته‌بندی", valueEN: "50 kg tightly sealed composite bag" },
      { labelFA: "استاندارد مرجع", labelEN: "Standard License", valueFA: "تیپ ۲ - پرتلند متوسط اصلاح‌شده فلات کشور", valueEN: "Type II Moderate Heat Cement Standard" },
      { labelFA: "گیرش اولیه", labelEN: "Initial Setting Time", valueFA: "۱۲۰ دقیقه کامل", valueEN: "120 minutes mechanical curing state" },
    ]
  },
  {
    id: "yazd-super-plaster-micronized",
    category: "cement",
    nameFA: "گچ سفید میکرونیزه پاششی صدف یزد",
    nameEN: "Sadaf Yazd Super Fine Plaster of Paris",
    descriptionFA: "گچ میکرونیزه با مش فوق‌العاده ریز ۲۰۰، فاقد زبری و دارای سفیدی خیره‌کننده، مناسب پردازش و پرداخت سفید کاری لوکس گچبری.",
    descriptionEN: "Double-ground premium white gypsum powder. High whiteness ratio, fast hydration bounds and extremely easy troweling on cellular drywall or concrete.",
    unitFA: "پاکت ۳۰ کیلویی",
    unitEN: "30KG Bag",
    pricePerUnitTomans: 39000,
    packWeightKG: 30,
    imageUrl: "https://images.unsplash.com/photo-1560185127-6a2806647f81?auto=format&fit=crop&q=80&w=600",
    featured: false,
    specifications: [
      { labelFA: "عیار مش پودر", labelEN: "Mesh Grain Size", valueFA: "مش ۲۰۰ میکرونیزه (طرح ابریشم بدون الک)", valueEN: "Mesh size 200 (needs no on-site sieving)" },
      { labelFA: "سفیدی", labelEN: "Whiteness Rate", valueFA: "۹۶٪ درجه درخشش بازتابی", valueEN: "96% reflective absolute snow white" },
      { labelFA: "مدت زمان گیرش ثانویه", labelEN: "Secondary Set Limit", valueFA: "۲۰ دقیقه کار مداوم جهت گچ‌بری", valueEN: "20 minutes malleable sculpting threshold" },
    ]
  },
  {
    id: "yazd-steel-rebar-14-alloy",
    category: "steel",
    nameFA: "میلگرد آجدار سایز ۱۴ فولاد آلیاژی یزد",
    nameEN: "A3 Ribbed Steel Rebar size 14 - Yazd Alloy",
    descriptionFA: "میلگرد شاخه‌ای ۱۲ متری عیار سخت آج جناقی هجده با ظرفیت تسلیم ۴۰۰ مگاپاسکال به عنوان شالوده ضد زلزله سازه بتنی.",
    descriptionEN: "Grade A3 ribbed steel reinforcement bars, size 14. 12-meter standard length. Delivering excellent concrete grip, tensile ductility, and high load capacity.",
    unitFA: "شاخه ۱۲ متری",
    unitEN: "12m Bar",
    pricePerUnitTomans: 385000, // price per bar (based on approx 14.5 kg weight)
    densityKGperM3: 7850,
    packWeightKG: 14.5,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600",
    featured: true,
    specifications: [
      { labelFA: "وزن هر شاخه", labelEN: "Bar Weight", valueFA: "۱۴.۵ کیلوگرم میانگین", valueEN: "~14.5 kg average structural deadweight" },
      { labelFA: "طرح آج مهندسی", labelEN: "Ribbed Pattern", valueFA: "آج جناقی جناقی ضربدری فشرده (رده A3)", valueEN: "Helical-cross configuration (Class A3)" },
      { labelFA: "تنش تسلیم نهایی", labelEN: "Tensile Yield Limit", valueFA: "۴۰۰۰ کیلوگرم بر سانتی‌متر مربع", valueEN: "4,000 kg/cm² ultimate stress resistance" },
    ]
  }
];

export const CALCULATORS: ProjectCalculatorType[] = [
  {
    id: "concrete-wall",
    icon: "BrickIcon",
    nameFA: "دیوار چینی (سفال و آجر)",
    nameEN: "Wall Masonry (Clay Blocks/Bricks)",
    descriptionFA: "تخمین هوشمند تعداد توام بلوک سفال یا آجر سنتی ملات سیمان، و بارهای جاده‌ای حمل بار.",
    descriptionEN: "Predict total hollow blocks or hand-made bricks, mortar mixes, and hauling weight limits.",
    formulaDescriptionFA: "محاسبه بر اساس ابعاد تایل محصول انتخابی؛ به طور متوسط ۲۵ عدد بلوک ۱۵ سانتی‌متری در هر متر مربع به همراه ۱۵ لیتر ملات ماسه سیمان به ضخامت متوسط ۱.۵ سانتی‌متر.",
    formulaDescriptionEN: "Calculated based on standard 20x20x15cm blocks requiring 25 units per square meter, including 15L of mortar per M2 with an average 1.5cm joint thickness.",
    inputs: [
      { id: "length", labelFA: "طول کل دیوار متراژ", labelEN: "Total Wall Length", unitFA: "متر طولی", unitEN: "Meters", defaultValue: 12, placeholder: "12" },
      { id: "height", labelFA: "ارتفاع کل دیوار", labelEN: "Total Wall Height", unitFA: "متر طولی", unitEN: "Meters", defaultValue: 3, placeholder: "3" },
      { id: "thickness", labelFA: "ضخامت دیوار", labelEN: "Wall Thickness", unitFA: "سانتی‌متر", unitEN: "cm", defaultValue: 15, placeholder: "15" }
    ]
  },
  {
    id: "concrete-slab",
    icon: "LayersIcon",
    nameFA: "بتن‌ریزی فونداسیون و سقف",
    nameEN: "Structural Concrete Slab",
    descriptionFA: "برآورد حجم دقیق بتن آماده بر حسب متر مکعب، پاکت‌های سیمان مورد نیاز و تخمین اوزان بار تریلی.",
    descriptionEN: "Estimate structural volume in Cubic Meters, bags of Portland cement for manual pours, and freight constraints.",
    formulaDescriptionFA: "حجم بتن = طول × عرض × ضخامت. هر متر مکعب بتن کارگاهی عیار ۳۵۰ نیاز به ۷ پاکت سیمان ۵۰ کیلویی و ۱.۲ تن شن و ماسه ترکیبی دارد.",
    formulaDescriptionEN: "Volume = Length x Width x Thickness. A standard high strength C25 mix incorporates ~350kg/m³ cement (7 bags) and 1.2 tons of sand/aggregates per m³.",
    inputs: [
      { id: "length", labelFA: "طول بخش بتن‌ریزی", labelEN: "Pouring Length", unitFA: "متر طولی", unitEN: "Meters", defaultValue: 10, placeholder: "10" },
      { id: "width", labelFA: "عرض بخش بتن‌ریزی", labelEN: "Pouring Width", unitFA: "متر", unitEN: "Meters", defaultValue: 5, placeholder: "5" },
      { id: "thickness", labelFA: "ضخامت بتن (عمق)", labelEN: "Slab Thickness / Depth", unitFA: "سانتی‌متر", unitEN: "cm", defaultValue: 20, placeholder: "20" }
    ]
  },
  {
    id: "tiling",
    icon: "LayoutGridIcon",
    nameFA: "سرامیک و کاشی‌کاری کف/دیوار",
    nameEN: "Flooring, Walls & Porcelain Tiles",
    descriptionFA: "محاسبه متراژ خالص کاشی پرسلان مورد نیاز به انضمام ۱۰٪ ضریب پرت کارگاهی و تخمین چسب سرامیک پاکتی.",
    descriptionEN: "Calculates tile sheets, recommended 10% wastage margins, and total bags of adhesive polymer powder.",
    formulaDescriptionFA: "متراژ کل = طول × عرض × ۱.۱۰ درصد ضریب هدررفت برش. برای نصب، هر متر مربع نیاز به ۵ کیلوگرم چسب پرسلان تقویت‌شده پودری دارد.",
    formulaDescriptionEN: "Total M² = Length x Width x 1.10 (margin factor of standard cut slivers). Adhesive requirement averages ~5kg of professional powder per M².",
    inputs: [
      { id: "length", labelFA: "طول سطح پوشش کاشی", labelEN: "Tiling Area Length", unitFA: "متر طولی", unitEN: "Meters", defaultValue: 8, placeholder: "8" },
      { id: "width", labelFA: "عرض سطح پوشش کاشی", labelEN: "Tiling Area Width", unitFA: "متر", unitEN: "Meters", defaultValue: 4, placeholder: "4" }
    ]
  }
];
